[workspace]
members = [
    "testing",
    "setup",
    "optimization",
    "simulation",
    "sim20",
    "sim-derive",
    "qrsim",
]

[profile.dev]
panic = "abort"

[profile.release]
lto = "thin"
panic = "abort"
