[package]
name = "simulation"
version = "0.1.0"
authors = ["Michal Siedlaczek <michal.siedlaczek@gmail.com>"]
edition = "2018"

[dependencies]
rand = "0.7"
rand_chacha = "0.2"
rand_distr = "0.2"
simulation-derive = { path = "../simulation-derive" }
log = "0.4"
